PluginViewer: fix NPE on plugin removal
java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(URI.java:3167)
	at org.apache.hc.client5.http.classic.methods.HttpGet.<init>(HttpGet.java:60)
	at org.jivesoftware.sparkimpl.plugin.viewer.PluginViewer.downloadPlugin(PluginViewer.java:383)
	at org.jivesoftware.sparkimpl.plugin.viewer.PluginViewer.access$600(PluginViewer.java:65)
	at org.jivesoftware.sparkimpl.plugin.viewer.PluginViewer$4$1.mouseClicked(PluginViewer.java:700)